// Per-page SEO metadata, derived from where each file actually sits.
//
//   node tools/seo.mjs           rewrite every page's metadata block + sitemap
//   node tools/seo.mjs --check   fail if anything is out of date (what CI runs)
//
// This exists because the canonical URLs were hand-typed, and ten of the eleven
// documentation pages ended up declaring the same one -- `/docs//`, with the
// slug missing and a doubled slash. A canonical pointing at another page is not
// a cosmetic defect: it tells a search engine "this page is a duplicate, index
// that one instead", so ten pages of documentation asked to be dropped from the
// index. Deriving the URL from the path is the only version of this that cannot
// drift, and the sitemap is written from the same walk so it cannot disagree.
//
// Everything between the markers is generated. Edit the title and description
// in the page itself -- those are the parts a human should be writing.
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const ORIGIN = 'https://neuron-workspace.github.io';
const IMAGE = `${ORIGIN}/og.png`;
const IMAGE_ALT =
  'The Neuron workspace: a file tree beside a Dashboard note in reading view, '
  + 'with a metric strip and task cards built from layout components.';

const START = '<!-- seo:start — generated by tools/seo.mjs; do not edit by hand -->';
const END = '<!-- seo:end -->';

/** Every .html file in the site, excluding this directory's own sources. */
function pages(dir = root, found = []) {
  for (const name of readdirSync(dir)) {
    if (name === '.git' || name === 'node_modules' || name === 'tools' || name === 'fonts') continue;
    const full = join(dir, name);
    if (statSync(full).isDirectory()) pages(full, found);
    else if (name.endsWith('.html')) found.push(full);
  }
  return found;
}

/**
 * The URL a page is actually served at.
 *
 * `index.html` is served as its directory, so it must canonicalise to the
 * directory -- otherwise `/docs/` and `/docs/index.html` are two URLs for one
 * page, which is the duplicate-content problem canonical tags exist to solve.
 */
export function canonicalPath(relativePath) {
  const url = relativePath.split(sep).join('/');
  if (url === 'index.html') return '/';
  if (url.endsWith('/index.html')) return `/${url.slice(0, -'index.html'.length)}`;
  return `/${url}`;
}

const between = (html, open, close) => {
  const start = html.indexOf(open);
  if (start === -1) return null;
  const end = html.indexOf(close, start + open.length);
  return end === -1 ? null : html.slice(start + open.length, end);
};

/** Attribute values go into HTML as attribute values, not as markup. */
const attr = (value) => value
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/**
 * Documentation pages are articles under a section; the landing pages are the
 * site itself. Search engines show the crumb trail in results, so it is worth
 * saying which is which.
 */
function breadcrumb(path) {
  const parts = path.split('/').filter(Boolean);
  if (!parts.length) return null;
  const items = [{ name: 'Neuron', url: `${ORIGIN}/` }];
  let at = '';
  for (const part of parts) {
    at += `/${part}`;
    const name = part
      .replace(/\.html$/, '')
      .replace(/-/g, ' ')
      .replace(/^./, (c) => c.toUpperCase());
    items.push({ name, url: `${ORIGIN}${at}${part.endsWith('.html') ? '' : '/'}` });
  }
  return {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: items.map((item, i) => ({
      '@type': 'ListItem', position: i + 1, name: item.name, item: item.url,
    })),
  };
}

function block(page) {
  const { path, title, description, isDocs } = page;
  const url = `${ORIGIN}${path}`;
  const lines = [
    START,
    `    <link rel="canonical" href="${url}" />`,
    '',
    `    <meta property="og:site_name" content="Neuron" />`,
    `    <meta property="og:locale" content="en" />`,
    `    <meta property="og:type" content="${isDocs ? 'article' : 'website'}" />`,
    `    <meta property="og:url" content="${url}" />`,
    `    <meta property="og:title" content="${attr(title)}" />`,
    `    <meta property="og:description" content="${attr(description)}" />`,
    `    <meta property="og:image" content="${IMAGE}" />`,
    `    <meta property="og:image:type" content="image/png" />`,
    `    <meta property="og:image:width" content="1200" />`,
    `    <meta property="og:image:height" content="630" />`,
    `    <meta property="og:image:alt" content="${attr(IMAGE_ALT)}" />`,
    '',
    `    <meta name="twitter:card" content="summary_large_image" />`,
    `    <meta name="twitter:title" content="${attr(title)}" />`,
    `    <meta name="twitter:description" content="${attr(description)}" />`,
    `    <meta name="twitter:image" content="${IMAGE}" />`,
    `    <meta name="twitter:image:alt" content="${attr(IMAGE_ALT)}" />`,
  ];
  const crumbs = breadcrumb(path);
  if (crumbs) {
    lines.push(
      '',
      '    <script type="application/ld+json">',
      `      ${JSON.stringify(crumbs)}`,
      '    </script>',
    );
  }
  lines.push(`    ${END}`);
  return lines.join('\n');
}

/** Replace the managed block, or insert one straight after the title. */
function apply(html, page) {
  const generated = block(page);
  const start = html.indexOf(START);
  if (start !== -1) {
    const end = html.indexOf(END, start);
    return html.slice(0, start) + generated.trimStart() + html.slice(end + END.length);
  }

  // First run on this page: drop whatever was hand-written, then insert. Scoped
  // to <head> so a documentation page that *describes* a meta tag in its prose
  // keeps its example.
  const headEnd = html.indexOf('</head>');
  let head = html.slice(0, headEnd);
  head = head
    .replace(/^[ \t]*<link[^>]*rel="canonical"[^>]*>\r?\n/gm, '')
    .replace(/^[ \t]*<meta[^>]*(?:property="og:|name="twitter:)[^>]*>\r?\n/gm, '');

  const titleEnd = head.indexOf('</title>');
  if (titleEnd === -1) throw new Error('no <title> to anchor the metadata block to');
  const at = titleEnd + '</title>'.length;
  return `${head.slice(0, at)}\n\n    ${generated}${head.slice(at)}${html.slice(headEnd)}`;
}

const all = pages()
  .map((file) => {
    const html = readFileSync(file, 'utf-8');
    const rel = relative(root, file);
    const title = between(html, '<title>', '</title>');
    const description = between(html, 'name="description" content="', '"');
    if (!title || !description) throw new Error(`${rel}: needs a <title> and a description`);
    return {
      file,
      rel,
      html,
      path: canonicalPath(rel),
      title: title.trim(),
      description: description.trim(),
      isDocs: rel.split(sep)[0] === 'docs',
      // A page telling robots not to index it has no business in the sitemap.
      noindex: /name="robots"[^>]*noindex/.test(html),
    };
  })
  .sort((a, b) => a.path.localeCompare(b.path));

const sitemap = [
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
  ...all.filter((p) => !p.noindex).map((p) => `  <url><loc>${ORIGIN}${p.path}</loc></url>`),
  '</urlset>',
  '',
].join('\n');

const check = process.argv.includes('--check');
const stale = [];

for (const page of all) {
  const next = apply(page.html, page);
  if (next === page.html) continue;
  stale.push(page.rel);
  if (!check) writeFileSync(page.file, next);
}

const sitemapFile = resolve(root, 'sitemap.xml');
let current = '';
try { current = readFileSync(sitemapFile, 'utf-8'); } catch { /* not written yet */ }
if (current !== sitemap) {
  stale.push('sitemap.xml');
  if (!check) writeFileSync(sitemapFile, sitemap);
}

if (check && stale.length) {
  console.error(`Out of date, run \`node tools/seo.mjs\`:\n  ${stale.join('\n  ')}`);
  process.exit(1);
}
console.log(check
  ? `seo: ${all.length} pages and the sitemap are up to date`
  : `seo: wrote ${stale.length || 'no'} change${stale.length === 1 ? '' : 's'} across ${all.length} pages`);
